# Generated by Django 6.0.5 on 2026-05-09 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='reservas.reserva'),
        ),
        migrations.AddField(
            model_name='pago',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='reservas.reserva'),
        ),
        migrations.AddField(
            model_name='factura',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagos.pago'),
        ),
    ]
