# Generated by Django 6.0.3 on 2026-05-09 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actividad', models.CharField(max_length=150)),
                ('descripcion_actividad', models.TextField(blank=True)),
                ('duracion_horas', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('descripcion_categoria', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paquete', models.CharField(max_length=150)),
                ('descripcion_paquete', models.TextField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_estimada', models.CharField(max_length=50)),
                ('capacidad_maxima', models.PositiveIntegerField(default=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='paquetes/')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField()),
                ('fecha_regreso', models.DateField()),
                ('cupos_disponibles', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='catalogo.paquete')),
            ],
        ),
        migrations.CreateModel(
            name='PaqueteActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.actividad')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='catalogo.paquete')),
            ],
            options={
                'unique_together': {('paquete', 'actividad')},
            },
        ),
    ]
