# Generated by Django 6.0.5 on 2026-05-09 14:13
# Generated by Django 6.0.5 on 2026-05-11 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Actividad')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('nivel_dificultad', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=10, verbose_name='Nivel de Dificultad')),
                ('equipo_requerimiento', models.TextField(verbose_name='Equipo Requerido')),
                ('recomendacion_salud', models.TextField(verbose_name='Recomendaciones de Salud')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Categoría')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='¿Está Activa?')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='destinos/')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Paquete')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.IntegerField(verbose_name='Precio Total')),
                ('duracion_estimada', models.CharField(max_length=50)),
                ('punto_encuentro', models.CharField(max_length=200)),
                ('codigo_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='PaqueteActividad',
            fields=[
                ('codigo_paquete_act', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.actividades')),
                ('codigo_paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.paquete')),
            ],
            options={
                'db_table': 'paquete_actividades',
            },
        ),
        migrations.AddField(
            model_name='paquete',
            name='actividades',
            field=models.ManyToManyField(through='catalogo.PaqueteActividad', to='catalogo.actividades'),
        ),
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actividades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("nivel_dificultad", models.CharField(max_length=50)),
                ("equipo_requerimiento", models.TextField()),
                ("recomendacion_salud", models.TextField()),
            ],
            options={
                "verbose_name": "Actividad",
                "verbose_name_plural": "Actividades",
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de la Categoría"
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "estado",
                    models.BooleanField(default=True, verbose_name="¿Está Activa?"),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
            },
        ),
        migrations.CreateModel(
            name="Paquete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="paquetes/"),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duracion_estimada", models.CharField(max_length=100)),
                ("punto_encuentro", models.CharField(max_length=200)),
                ("actividades", models.ManyToManyField(to="catalogo.actividades")),
                (
                    "codigo_categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogo.categoria",
                    ),
                ),
            ],
        ),
    ]
