# Generated by Django 6.0.5 on 2026-05-09 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_promocion', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='promociones/')),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaquetePromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.paquete')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promociones.promocion')),
            ],
            options={
                'unique_together': {('paquete', 'promocion')},
            },
        ),
    ]
