# Generated by Django 6.1 on 2026-08-28 15:57

import App.models
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Actividad')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('equipo_requerimiento', models.TextField(blank=True, null=True, verbose_name='Equipo Requerido')),
                ('recomendaciones', models.TextField(blank=True, null=True, verbose_name='Recomendaciones')),
                ('estado', models.BooleanField(blank=True, default=True, verbose_name='¿Está Activa?')),
                ('apto_menores', models.BooleanField(default=True, verbose_name='¿Apto para menores?')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='¿Está Activa?')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='PolizaViaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_poliza', models.CharField(max_length=150, verbose_name='Nombre de la Póliza')),
                ('descripcion', models.TextField(verbose_name='Descripción de Coberturas')),
                ('cobertura_medica_max', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto máximo de cobertura médica')),
                ('cubre_perdida_equipaje', models.BooleanField(default=False, verbose_name='¿Cubre pérdida de equipaje?')),
                ('cubre_cancelacion_vuelo', models.BooleanField(default=False, verbose_name='¿Cubre cancelación de vuelo?')),
                ('precio_diario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por Día')),
                ('condiciones_generales', models.TextField(blank=True, null=True, verbose_name='Condiciones Generales')),
                ('estado', models.BooleanField(default=True, verbose_name='¿Póliza Activa?')),
            ],
            options={
                'verbose_name': 'Póliza de Viaje',
                'verbose_name_plural': 'Pólizas de Viaje',
            },
        ),
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('peticion', 'Petición'), ('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia')], max_length=15)),
                ('asunto', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En Proceso'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'PQRS',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la promoción')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('porcentaje_descuento', models.PositiveIntegerField(verbose_name='Porcentaje de descuento')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('codigo_promocion', models.CharField(max_length=20, unique=True, verbose_name='Código de promoción')),
                ('condiciones', models.TextField(blank=True, null=True, verbose_name='Condiciones')),
                ('codigo_cupon', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Código de cupón')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Activa?')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Temporada')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción de la Temporada')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('estado', models.BooleanField(default=True, verbose_name='¿Está Activa?')),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='destinos/', verbose_name='Imagen del Destino')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Paquete')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('dias_duracion', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Los días de duración deben ser al menos 1.')], verbose_name='Días de Duración')),
                ('noches_duracion', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Las noches de duración deben ser al menos 1.')], verbose_name='Noches de Duración')),
                ('punto_encuentro', models.CharField(max_length=150, validators=[App.models.validar_punto_encuentro], verbose_name='Punto de Encuentro')),
                ('hora_encuentro', models.TimeField()),
                ('estado', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='App.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='PaqueteActividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dificultad_nivel', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Media', max_length=10, verbose_name='Nivel de Dificultad')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.actividades')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.paquete')),
            ],
            options={
                'verbose_name': 'Actividad del Paquete',
                'verbose_name_plural': 'Actividades del Paquete',
                'db_table': 'paquete_actividades',
                'unique_together': {('paquete', 'actividad')},
            },
        ),
        migrations.AddField(
            model_name='paquete',
            name='actividades',
            field=models.ManyToManyField(through='App.PaqueteActividad', to='App.actividades'),
        ),
        migrations.CreateModel(
            name='PaquetePromocion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor_adulto_condescuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Adulto con Descuento')),
                ('valor_menor_condescuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Menor con Descuento')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.paquete')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.promocion')),
            ],
            options={
                'verbose_name': 'Promoción del Paquete',
                'verbose_name_plural': 'Promociones del Paquete',
                'db_table': 'paquete_promocion',
                'unique_together': {('paquete', 'promocion')},
            },
        ),
        migrations.AddField(
            model_name='paquete',
            name='promociones',
            field=models.ManyToManyField(blank=True, through='App.PaquetePromocion', to='App.promocion', verbose_name='Promociones'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('numero_adultos', models.PositiveSmallIntegerField(default=1, verbose_name='Número de Adultos')),
                ('numero_menores', models.PositiveSmallIntegerField(default=0, verbose_name='Número de Menores')),
                ('estado_reserva', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('motivo_cancelacion', models.TextField(blank=True, null=True, verbose_name='Motivo de Cancelación')),
                ('monto_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Monto Total')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='App.paquete', verbose_name='Paquete Reservado')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('referencia', models.CharField(help_text='Número de comprobante, transacción o referencia bancaria', max_length=100, verbose_name='Número de referencia / transacción')),
                ('banco_origen', models.CharField(max_length=100, verbose_name='Banco / medio de pago')),
                ('metodo_pago', models.CharField(max_length=50, verbose_name='Método de Pago')),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto pagado')),
                ('imagen_comprobante', models.ImageField(upload_to='comprobantes/%Y/%m/', verbose_name='Imagen del comprobante')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción / nota adicional')),
                ('estado_transaccion', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('nota_admin', models.TextField(blank=True, verbose_name='Nota del administrador')),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha exacta del pago bancario')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='App.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pago',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(default='experiencia', help_text='Tipo de reseña: experiencia, pregunta, etc.', max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('puntaje_estrellas', App.models.PositiveTinyIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1, message='La calificación mínima es 1 estrella.'), django.core.validators.MaxValueValidator(5, message='La calificación máxima es 5 estrellas.')], verbose_name='Puntaje / Estrellas')),
                ('comentario', models.TextField(verbose_name='Comentario / Reseña')),
                ('visible', models.BooleanField(default=True, verbose_name='¿Visible?')),
                ('admin_respuesta', models.TextField(blank=True, null=True, verbose_name='Respuesta del Admin')),
                ('fecha_calificacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Calificación')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones', to='App.reserva', verbose_name='Reserva Calificada')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'comunidad_calificacion',
                'ordering': ['-fecha_calificacion'],
            },
        ),
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la Empresa Aseguradora')),
                ('numero_poliza', models.CharField(max_length=100, unique=True, verbose_name='Número de Póliza Emitida')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('fecha_inicio_cobertura', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio de Cobertura')),
                ('fecha_fin_cobertura', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin de Cobertura')),
                ('costo_seguro', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Costo de Seguro')),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Emergencia')),
                ('estado_emision', models.CharField(default='Pendiente', max_length=20, verbose_name='Estado de Emisión')),
                ('poliza_viaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aseguradoras', to='App.polizaviaje', verbose_name='Póliza de Viaje Asociada')),
                ('reserva', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aseguradora', to='App.reserva', verbose_name='Reserva Asociada')),
            ],
            options={
                'verbose_name': 'Seguro Emitido (Aseguradora)',
                'verbose_name_plural': 'Seguros Emitidos (Aseguradoras)',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(error_messages={'unique': 'Ya existe un usuario registrado con este correo electrónico.'}, max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último inicio de sesión')),
                ('rol', models.PositiveSmallIntegerField(choices=[(1, 'Administrador'), (2, 'Cliente'), (3, 'Guía Turístico')], default=2, verbose_name='Rol')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PASAPORTE', 'Pasaporte')], max_length=20, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, verbose_name='Número de Documento')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('residencia', models.CharField(blank=True, max_length=100, verbose_name='Residencia de Origen')),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Imagen de Perfil')),
                ('pais', models.CharField(blank=True, max_length=3, verbose_name='País')),
                ('departamento', models.IntegerField(blank=True, null=True, verbose_name='Departamento')),
                ('ciudad', models.IntegerField(blank=True, null=True, verbose_name='Ciudad')),
                ('numero_tarjeta_profesional', models.CharField(blank=True, max_length=50, null=True, verbose_name='Licencia de Turismo')),
                ('experiencia_anos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Años de Experiencia')),
                ('experiencia_fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio de Experiencia')),
                ('descripcion_experiencia', models.TextField(blank=True, null=True, verbose_name='Descripción de la Experiencia')),
                ('entidad_salud', models.CharField(blank=True, max_length=100, null=True, verbose_name='Entidad de Salud')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.TextField(verbose_name='Mensaje / Respuesta')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Respuesta')),
                ('pqrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='App.pqrs', verbose_name='PQRS')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='App.reserva', verbose_name='Reserva Asociada')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario / Administrador')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'db_table': 'seguimiento',
                'ordering': ['fecha_respuesta'],
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='pqrs',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pqrs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PlanGuia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idioma_servicio', models.CharField(max_length=50, verbose_name='Idioma del Servicio')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_inicio_plan', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin_plan', models.DateField(verbose_name='Fecha de Fin')),
                ('estado', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_guia', to='App.paquete', verbose_name='Paquete')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_guia', to=settings.AUTH_USER_MODEL, verbose_name='Usuario / Guía')),
            ],
            options={
                'verbose_name': 'Plan Guía',
                'verbose_name_plural': 'Planes Guía',
                'db_table': 'plan_guia',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField(verbose_name='Mensaje de la Notificación')),
                ('leido', models.BooleanField(default=False, verbose_name='¿Leído?')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de Notificación')),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=20, verbose_name='Prioridad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='App.reserva', verbose_name='Reserva')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificacion',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('informacion_adicional', models.TextField(blank=True, null=True, verbose_name='Información Adicional')),
                ('imagen_destacada', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True, verbose_name='¿Está Publicado?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs_publicados', to=settings.AUTH_USER_MODEL, verbose_name='Autor / Administrador')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(choices=[('INSERT', 'Creación / Registro'), ('UPDATE', 'Modificación / Actualización'), ('DELETE', 'Eliminación'), ('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('ACCESO', 'Acceso / Consulta'), ('RESPUESTA', 'Respuesta / Seguimiento'), ('NOTIFICACION', 'Notificación de Sistema')], default='UPDATE', max_length=50, verbose_name='Acción Realizada')),
                ('modulo', models.CharField(db_index=True, default='General', max_length=100, verbose_name='Módulo / Tabla Afectada')),
                ('registro_id', models.BigIntegerField(blank=True, db_index=True, help_text='Identificador numérico del registro modificado en la tabla.', null=True, verbose_name='ID del Registro')),
                ('fecha_registro', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha y Hora del Registro')),
                ('ip_origen', models.GenericIPAddressField(blank=True, help_text='Dirección IPv4 o IPv6 desde donde se ejecutó la acción.', null=True, verbose_name='Dirección IP de Origen')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción / Observaciones')),
                ('datos_previos', models.JSONField(blank=True, help_text='Estado previo del registro antes del cambio (NULL en creaciones).', null=True, verbose_name='Datos Previos (JSON)')),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Estado posterior del registro tras el cambio (NULL en eliminaciones).', null=True, verbose_name='Datos Nuevos (JSON)')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to='App.pago', verbose_name='Pago Asociado')),
                ('pqrs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to='App.pqrs', verbose_name='PQRS Asociada')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to='App.reserva', verbose_name='Reserva Asociada')),
                ('seguimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to='App.seguimiento', verbose_name='Seguimiento Asociado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable')),
            ],
            options={
                'verbose_name': 'Bitácora',
                'verbose_name_plural': 'Bitácoras',
                'db_table': 'bitacora',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio_adulto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio por Adulto')),
                ('precio_menor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio por Menor')),
                ('estado', models.BooleanField(default=True, verbose_name='¿Está Activa?')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='App.paquete')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='App.temporada')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'unique_together': {('paquete', 'temporada')},
            },
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('usuario', 'paquete', 'fecha_inicio'), name='unique_usuario_paquete_fecha_inicio'),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['modulo', 'registro_id'], name='idx_bitacora_modulo_reg'),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['usuario', '-fecha_registro'], name='idx_bitacora_usr_fecha'),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['seguimiento'], name='idx_bitacora_seguimiento'),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['reserva'], name='idx_bitacora_reserva'),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['pqrs'], name='idx_bitacora_pqrs'),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['pago'], name='idx_bitacora_pago'),
        ),
    ]
