# Generated by Django 6.0.5 on 2026-08-25 19:53

import App.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Actividad')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('nivel_dificultad', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=10, verbose_name='Nivel de Dificultad')),
                ('equipo_requerimiento', models.TextField(verbose_name='Equipo Requerido')),
                ('recomendaciones', models.TextField(verbose_name='Recomendaciones')),
                ('estado', models.BooleanField(blank=True, default=True, verbose_name='¿Está Activa?')),
                ('apto_menores', models.BooleanField(default=True, verbose_name='¿Apto para menores?')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Categoría')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='¿Está Activa?')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('peticion', 'Petición'), ('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia')], max_length=15)),
                ('asunto', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En Proceso'), ('cerrado', 'Cerrado')], default='abierto', max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'PQRS',
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Temporada')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Temporada')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('activa', 'Activa'), ('finalizada', 'Finalizada')], default='programada', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='destinos/', verbose_name='Imagen del Destino')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Paquete')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('dias_duracion', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Los días de duración deben ser al menos 1.')], verbose_name='Días de Duración')),
                ('noches_duracion', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Las noches de duración deben ser al menos 1.')], verbose_name='Noches de Duración')),
                ('punto_encuentro', models.CharField(max_length=200, validators=[App.models.validar_punto_encuentro])),
                ('hora_encuentro', models.TimeField()),
                ('estado', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='App.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='PaqueteActividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dificultad_nivel', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Media', max_length=10, verbose_name='Nivel de Dificultad')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.actividades')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.paquete')),
            ],
            options={
                'verbose_name': 'Actividad del Paquete',
                'verbose_name_plural': 'Actividades del Paquete',
                'db_table': 'paquete_actividades',
            },
        ),
        migrations.AddField(
            model_name='paquete',
            name='actividades',
            field=models.ManyToManyField(through='App.PaqueteActividad', to='App.actividades'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(error_messages={'unique': 'Ya existe un usuario registrado con este correo electrónico.'}, max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('CLIENTE', 'Cliente'), ('GUIA', 'Guía Turístico')], default='CLIENTE', max_length=20, verbose_name='Rol')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PASAPORTE', 'Pasaporte')], max_length=20, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, verbose_name='Número de Documento')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('residencia', models.CharField(blank=True, max_length=100, verbose_name='Residencia de Origen')),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Imagen de Perfil')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.TextField(verbose_name='Mensaje / Respuesta')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Respuesta')),
                ('pqrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='App.pqrs')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario / Administrador')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'db_table': 'seguimiento',
                'ordering': ['fecha_respuesta'],
            },
        ),
        migrations.AddField(
            model_name='pqrs',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pqrs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('informacion_adicional', models.TextField(blank=True)),
                ('imagen_destacada', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True, verbose_name='¿Está Publicado?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs_publicados', to=settings.AUTH_USER_MODEL, verbose_name='Autor / Administrador')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio_adulto', models.IntegerField(verbose_name='Precio por Adulto')),
                ('precio_menor', models.IntegerField(verbose_name='Precio por Menor')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=10)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='App.paquete')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='App.temporada')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'unique_together': {('paquete', 'temporada')},
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha de Reserva')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('numero_adultos', models.PositiveIntegerField(default=1, verbose_name='Número de Adultos')),
                ('numero_menores', models.PositiveIntegerField(default=0, verbose_name='Número de Menores')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('motivo_cancelacion', models.TextField(blank=True, null=True, verbose_name='Motivo de Cancelación')),
                ('monto_total', models.IntegerField(editable=False, verbose_name='Monto Total')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='App.paquete', verbose_name='Paquete Reservado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'paquete', 'fecha'), name='unique_usuario_paquete_fecha')],
            },
        ),
    ]
