# Generated by Django 6.0.3 on 2026-05-09 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado')], default='programado', max_length=15)),
                ('notas', models.TextField(blank=True)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes', to='usuarios.guiaturistico')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.paquete')),
            ],
        ),
    ]
