# Generated by Django 6.0.5 on 2026-05-09 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('guias', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planguia',
            name='guia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes', to='usuarios.guiaturistico'),
        ),
        migrations.AddField(
            model_name='planguia',
            name='paquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.paquete'),
        ),
    ]
