# Generated by Django 6.0.3 on 2026-05-09 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('resumen', models.CharField(blank=True, max_length=300)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('categoria', models.CharField(blank=True, max_length=80)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('publicado', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Pqrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('peticion', 'Petición'), ('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia')], max_length=15)),
                ('asunto', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En Proceso'), ('cerrado', 'Cerrado')], default='abierto', max_length=15)),
                ('respuesta', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pqrs', to='usuarios.cliente')),
            ],
            options={
                'verbose_name_plural': 'PQRS',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.paquete')),
            ],
            options={
                'unique_together': {('cliente', 'paquete')},
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='usuarios.cliente')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.paquete')),
            ],
            options={
                'unique_together': {('cliente', 'paquete')},
            },
        ),
    ]
