# Generated by Django 6.0.5 on 2026-05-14 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('comunidad', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='paquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.paquete'),
        ),
        migrations.AddField(
            model_name='pqrs',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pqrs', to='usuarios.cliente'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('cliente', 'paquete')},
        ),
    ]
