# Generated by Django 6.0.5 on 2026-05-14 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('penalidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Reserva')),
                ('numero_personas', models.PositiveIntegerField(verbose_name='Número de Personas')),
                ('monto_total', models.IntegerField(editable=False, verbose_name='Monto Total')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserva', to='catalogo.paquete', verbose_name='Paquete Reservado')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
