# Generated by Django 6.0.5 on 2026-05-09 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('reservas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='usuarios.cliente'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='paquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.paquete'),
        ),
        migrations.AddField(
            model_name='cancelacion',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva'),
        ),
        migrations.AddField(
            model_name='seguroviaje',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva'),
        ),
    ]
